export const createMenuActions = (handlers) => ({
  file: {
    newFile: handlers.handleNewFile,
    newWindow: handlers.handleNewWindow,
    newFolder: handlers.handleNewFolder,
    openFile: handlers.handleOpenLocalFile,
    openWorkspaceFile: handlers.handleOpenFile,
    openFolder: handlers.handleOpenFolder,
    openRecent: handlers.handleOpenRecent,
    save: handlers.handleSave,
    saveAll: handlers.handleSaveAll,
    saveAs: handlers.handleSaveAs,
    closeFile: handlers.handleCloseFile,
    closeFolder: handlers.handleCloseFolder,
    downloadProject: handlers.handleDownloadProject,
    shareProject: handlers.handleShareProject,
    leaveRoomOrExit: handlers.handleLeaveRoomOrExit,
    exit: handlers.handleExit,
  },
  edit: {
    undo: handlers.handleUndo,
    redo: handlers.handleRedo,
    cut: handlers.handleCut,
    copy: handlers.handleCopy,
    paste: handlers.handlePaste,
    find: handlers.handleFind,
    replace: handlers.handleReplace,
    findInFiles: handlers.handleFindInFiles,
    replaceInFiles: handlers.handleReplaceInFiles,
    toggleLineComment: handlers.handleToggleLineComment,
    toggleBlockComment: handlers.handleToggleBlockComment,
    emmetExpandAbbreviation: handlers.handleEmmetExpandAbbreviation,
    addCursorAbove: handlers.handleAddCursorAbove,
    addCursorBelow: handlers.handleAddCursorBelow,
    copyLineUp: handlers.handleCopyLineUp,
    copyLineDown: handlers.handleCopyLineDown,
  },
  view: {
    commandPalette: handlers.handleViewCommandPalette,
    openView: handlers.handleViewOpenView,
    appearanceFullScreen: handlers.handleToggleFullScreen,
    appearanceZenMode: handlers.handleToggleZenMode,
    appearanceCenteredLayout: handlers.handleToggleCenteredLayout,
    appearanceShowMenuBar: handlers.handleToggleShowMenuBar,
    appearanceShowStatusBar: handlers.handleToggleShowStatusBar,
    appearanceShowActivityBar: handlers.handleToggleShowActivityBar,
    appearanceShowSideBar: handlers.handleToggleShowSideBar,
    explorer: handlers.handleOpenExplorerView,
    search: handlers.handleOpenSearchView,
    sourceControl: handlers.handleOpenSourceControlView,
    runAndDebug: handlers.handleOpenRunDebugView,
    extensions: handlers.handleOpenExtensionsView,
    problems: handlers.handleOpenProblemsPanel,
    output: handlers.handleOpenOutputPanel,
    debugConsole: handlers.handleOpenDebugConsolePanel,
    terminal: handlers.handleOpenTerminalPanel,
    wordWrap: handlers.handleToggleWordWrap,
    showMinimap: handlers.handleToggleMinimap,
    showBreadcrumbs: handlers.handleToggleBreadcrumbs,
    toggleSidebar: handlers.handleToggleSidebar,
    zoomIn: handlers.handleZoomIn,
    zoomOut: handlers.handleZoomOut,
    toggleFullScreen: handlers.handleToggleFullScreen,
  },
  selection: {
    selectAll: handlers.handleSelectAll,
    addCursorAbove: handlers.handleAddCursorAbove,
    addCursorBelow: handlers.handleAddCursorBelow,
  },
  go: {
    goToFile: handlers.handleGoToFile,
    previousFile: handlers.handleGoToPreviousFile,
    nextFile: handlers.handleGoToNextFile,
    goToLine: handlers.handleGoToLine,
  },
  run: {
    startDebugging: handlers.handleStartDebugging,
    runWithoutDebugging: handlers.handleRunWithoutDebugging,
    stopDebugging: handlers.handleStopDebugging,
    restartDebugging: handlers.handleRestartDebugging,
    openConfigurations: handlers.handleOpenRunConfigurations,
    addConfiguration: handlers.handleAddRunConfiguration,
    toggleBreakpoint: handlers.handleToggleBreakpoint,
    enableAllBreakpoints: handlers.handleEnableAllBreakpoints,
    disableAllBreakpoints: handlers.handleDisableAllBreakpoints,
    removeAllBreakpoints: handlers.handleRemoveAllBreakpoints,
    stepOver: handlers.handleStepOver,
    stepInto: handlers.handleStepInto,
    stepOut: handlers.handleStepOut,
    continueExecution: handlers.handleContinueExecution,
    runCode: handlers.handleRunCode,
    showOutput: handlers.handleNewTerminal,
  },
  terminal: {
    newTerminal: handlers.handleNewTerminal,
    splitTerminal: handlers.handleSplitTerminal,
    runTask: handlers.handleRunTask,
    runBuildTask: handlers.handleRunBuildTask,
    runActiveFile: handlers.handleRunActiveFile,
    runSelectedText: handlers.handleRunSelectedText,
    killTerminal: handlers.handleKillTerminal,
    clearTerminal: handlers.handleClearTerminal,
    focusTerminal: handlers.handleFocusTerminal,
    moveTerminalToEditorArea: handlers.handleMoveTerminalToEditorArea,
    toggleTerminal: handlers.handleToggleTerminal,
    runCommand: handlers.handleRunTask,
  },
  help: {
    keyboardShortcuts: handlers.handleKeyboardShortcuts,
    about: handlers.handleAbout,
  },
});

export const getMenuSections = () => ([
  {
    key: 'file',
    label: 'File',
    icon: '📁',
    items: [
      { label: 'New File', action: 'newFile', shortcut: 'Ctrl+N' },
      { label: 'New Window', action: 'newWindow', shortcut: 'Ctrl+Shift+N' },
      { label: 'New Folder', action: 'newFolder' },
      { label: 'Open File from Device...', action: 'openFile' },
      { label: 'Open File', action: 'openWorkspaceFile', shortcut: 'Ctrl+O' },
      { label: 'Open Folder from Device', action: 'openFolder' },
      { label: 'Open Recent...', action: 'openRecent' },
      { label: 'Save', action: 'save', shortcut: 'Ctrl+S' },
      { label: 'Save All', action: 'saveAll' },
      { label: 'Save As', action: 'saveAs', shortcut: 'Ctrl+Shift+S' },
      { label: 'Close File', action: 'closeFile' },
      { label: 'Leave Room / Exit', action: 'leaveRoomOrExit' },
      { label: 'Close Folder', action: 'closeFolder' },
      { label: 'Download Project ZIP', action: 'downloadProject' },
      { label: 'Share Project', action: 'shareProject' },
      { label: 'Exit', action: 'exit' },
    ],
  },
  {
    key: 'edit',
    label: 'Edit',
    icon: '✏️',
    items: [
      { label: 'Undo', action: 'undo', shortcut: 'Ctrl+Z' },
      { label: 'Redo', action: 'redo', shortcut: 'Ctrl+Y / Ctrl+Shift+Z' },
      { label: 'Cut', action: 'cut', shortcut: 'Ctrl+X' },
      { label: 'Copy', action: 'copy', shortcut: 'Ctrl+C' },
      { label: 'Paste', action: 'paste', shortcut: 'Ctrl+V' },
      {
        label: 'Find',
        children: [
          { label: 'Find', action: 'find', shortcut: 'Ctrl+F' },
          { label: 'Replace', action: 'replace', shortcut: 'Ctrl+H' },
          { label: 'Find in Files', action: 'findInFiles', shortcut: 'Ctrl+Shift+F' },
          {
            label: 'More',
            children: [
              { label: 'Replace in Files', action: 'replaceInFiles', shortcut: 'Ctrl+Shift+H' },
              { label: 'Toggle Line Comment', action: 'toggleLineComment', shortcut: 'Ctrl+/' },
              { label: 'Toggle Block Comment', action: 'toggleBlockComment', shortcut: 'Shift+Alt+A' },
            ],
          },
        ],
      },
      { label: 'Toggle Line Comment', action: 'toggleLineComment', shortcut: 'Ctrl+/' },
      { label: 'Toggle Block Comment', action: 'toggleBlockComment', shortcut: 'Shift+Alt+A' },
      { label: 'Emmet: Expand Abbreviation', action: 'emmetExpandAbbreviation', shortcut: 'Tab' },
      { label: 'Add Cursor Above', action: 'addCursorAbove', shortcut: 'Ctrl+Alt+Up' },
      { label: 'Add Cursor Below', action: 'addCursorBelow', shortcut: 'Ctrl+Alt+Down' },
      { label: 'Copy Line Up', action: 'copyLineUp', shortcut: 'Shift+Alt+Up' },
      { label: 'Copy Line Down', action: 'copyLineDown', shortcut: 'Shift+Alt+Down' },
    ],
  },
  {
    key: 'view',
    label: 'View',
    icon: '👁️',
    items: [
      { label: 'Command Palette', action: 'commandPalette', shortcut: 'Ctrl+Shift+P' },
      { label: 'Open View', action: 'openView' },
      { label: 'Appearance: Full Screen', action: 'appearanceFullScreen', shortcut: 'F11' },
      { label: 'Appearance: Zen Mode', action: 'appearanceZenMode' },
      { label: 'Appearance: Centered Layout', action: 'appearanceCenteredLayout' },
      { label: 'Appearance: Show Menu Bar', action: 'appearanceShowMenuBar' },
      { label: 'Appearance: Show Status Bar', action: 'appearanceShowStatusBar' },
      { label: 'Appearance: Show Activity Bar', action: 'appearanceShowActivityBar' },
      { label: 'Appearance: Show Side Bar', action: 'appearanceShowSideBar' },
      { label: 'Explorer', action: 'explorer' },
      { label: 'Search', action: 'search' },
      { label: 'Source Control', action: 'sourceControl' },
      { label: 'Run and Debug', action: 'runAndDebug' },
      { label: 'Extensions', action: 'extensions' },
      { label: 'Problems', action: 'problems' },
      { label: 'Output', action: 'output' },
      { label: 'Debug Console', action: 'debugConsole' },
      { label: 'Terminal', action: 'terminal', shortcut: 'Ctrl+`' },
      { label: 'Word Wrap', action: 'wordWrap', shortcut: 'Alt+Z' },
      { label: 'Show Minimap', action: 'showMinimap' },
      { label: 'Show Breadcrumbs', action: 'showBreadcrumbs' },
      { label: 'Toggle Sidebar', action: 'toggleSidebar', shortcut: 'Ctrl+B' },
      { label: 'Zoom In', action: 'zoomIn', shortcut: 'Ctrl++' },
      { label: 'Zoom Out', action: 'zoomOut', shortcut: 'Ctrl+-' },
      { label: 'Toggle Full Screen', action: 'toggleFullScreen', shortcut: 'F11' },
    ],
  },
  {
    key: 'selection',
    label: 'Selection',
    icon: '🖱️',
    items: [
      { label: 'Select All', action: 'selectAll', shortcut: 'Ctrl+A' },
      { label: 'Add Cursor Above', action: 'addCursorAbove', shortcut: 'Ctrl+Alt+Up' },
      { label: 'Add Cursor Below', action: 'addCursorBelow', shortcut: 'Ctrl+Alt+Down' },
    ],
  },
  {
    key: 'go',
    label: 'Go',
    icon: '🧭',
    items: [
      { label: 'Go to File', action: 'goToFile', shortcut: 'Ctrl+P' },
      { label: 'Previous File', action: 'previousFile', shortcut: 'Alt+Left' },
      { label: 'Next File', action: 'nextFile', shortcut: 'Alt+Right' },
      { label: 'Go to Line', action: 'goToLine', shortcut: 'Ctrl+G' },
    ],
  },
  {
    key: 'run',
    label: 'Run',
    icon: '▶️',
    items: [
      { label: 'Start Debugging', action: 'startDebugging', shortcut: 'F5' },
      { label: 'Run Without Debugging', action: 'runWithoutDebugging', shortcut: 'Ctrl+F5' },
      { label: 'Stop Debugging', action: 'stopDebugging', shortcut: 'Shift+F5' },
      { label: 'Restart Debugging', action: 'restartDebugging', shortcut: 'Ctrl+Shift+F5' },
      { label: 'Open Configurations', action: 'openConfigurations' },
      { label: 'Add Configuration', action: 'addConfiguration' },
      { label: 'Toggle Breakpoint', action: 'toggleBreakpoint', shortcut: 'F9' },
      { label: 'Enable All Breakpoints', action: 'enableAllBreakpoints' },
      { label: 'Disable All Breakpoints', action: 'disableAllBreakpoints' },
      { label: 'Remove All Breakpoints', action: 'removeAllBreakpoints' },
      { label: 'Step Over', action: 'stepOver', shortcut: 'F10' },
      { label: 'Step Into', action: 'stepInto', shortcut: 'F11' },
      { label: 'Step Out', action: 'stepOut', shortcut: 'Shift+F11' },
      { label: 'Continue', action: 'continueExecution', shortcut: 'F5' },
    ],
  },
  {
    key: 'terminal',
    label: 'Terminal',
    icon: '💻',
    items: [
      { label: 'New Terminal', action: 'newTerminal' },
      { label: 'Split Terminal', action: 'splitTerminal' },
      { label: 'Run Task', action: 'runTask' },
      { label: 'Run Build Task', action: 'runBuildTask' },
      { label: 'Run Active File', action: 'runActiveFile' },
      { label: 'Run Selected Text', action: 'runSelectedText' },
      { label: 'Kill Terminal', action: 'killTerminal' },
      { label: 'Clear Terminal', action: 'clearTerminal' },
      { label: 'Focus Terminal', action: 'focusTerminal' },
      { label: 'Move Terminal to Editor Area', action: 'moveTerminalToEditorArea' },
      { label: 'Toggle Terminal', action: 'toggleTerminal', shortcut: 'Ctrl+`' },
    ],
  },
  {
    key: 'help',
    label: 'Help',
    icon: '❔',
    items: [
      { label: 'Keyboard Shortcuts', action: 'keyboardShortcuts' },
      { label: 'About Sync Code', action: 'about' },
    ],
  },
]);
